version: "3.9"
services:
  twenty-dev:
    build: 
      context: ../../..
      dockerfile: ./packages/twenty-docker/dev/twenty-dev/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ../../..:/app
      - twenty_dev_node_modules_root:/app/node_modules
      - twenty_dev_node_modules_docs:/app/packages/twenty-docs/node_modules
      - twenty_dev_node_modules_front:/app/packages/twenty-front/node_modules
      - twenty_dev_node_modules_server:/app/packages/twenty-server/node_modules
      - twenty_dev_node_modules_website:/app/packages/twenty-website/node_modules
      - twenty_dev_node_modules_zapier:/app/packages/twenty-zapier/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: twenty_postgres
    image: twentycrm/twenty-postgres:latest
    volumes:
    - twenty_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
volumes:
  twenty_db_data:
    name: twenty_db_data
  twenty_dev_node_modules_root:
  twenty_dev_node_modules_docs:
  twenty_dev_node_modules_eslint:
  twenty_dev_node_modules_front:
  twenty_dev_node_modules_server:
  twenty_dev_node_modules_website:
  twenty_dev_node_modules_zapier:

