version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    versioning-strategy: "lockfile-only"
    assignees:
      - "mabdullahabaid"
    ignore:
      - dependency-name: "@graphql-yoga/nestjs"
      - dependency-name: "@nestjs/graphql"
      - dependency-name: "@ptc-org/nestjs-query-graphql"
      - dependency-name: "typeorm"
