services:
- type: web
  name: front
  env: docker
  dockerfilePath: ./infra/prod/front/Dockerfile
  autoDeploy: false
  envVars:
  - key: REACT_APP_SERVER_BASE_URL
    fromService:
      name: server
      type: web
      envVarKey: RENDER_EXTERNAL_URL
- type: web
  name: server
  env: docker
  dockerfilePath: ./infra/prod/server/Dockerfile
  dockerCommand: echo 'Starting server...' && tail -f /dev/null
  autoDeploy: false
  envVars:
  - key: ACCESS_TOKEN_SECRET
    generateValue: true
  - key: LOGIN_TOKEN_SECRET
    generateValue: true
  - key: REFRESH_TOKEN_SECRET
    generateValue: true
  - key: IS_CORS_ENABLED
    value: false
  - key: PG_DATABASE_URL
    fromDatabase:
      name: twenty-db
      property: connectionString
  - key: FRONT_BASE_URL
    fromService:
      name: front
      type: web
      envVarKey: RENDER_EXTERNAL_URL
  disk:
    name: twenty-disk
    mountPath: /.local-storage
    sizeGB: 5

databases:
- name: twenty-db
  plan: starter
