{{- if and .Values.db.createUserHook.enabled (or .Values.postgresql.enabled .Values.db.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.createUserHook.secretName | default (printf "%s-db-user" (include "twenty.fullname" .)) }}
  namespace: {{ include "twenty.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "twenty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db-user
type: Opaque
{{- $pwd := (default (randAlphaNum 24) .Values.db.createUserHook.password) }}
stringData:
  username: {{ .Values.db.createUserHook.username | quote }}
  password: {{ $pwd | quote }}
{{- end }}
